name: ping url
description: ping url until maximum trials have exceeded. if result is not 200 until then fails the action.

inputs:
  url:
    required: true
    description: url to ping
  max_trials:
    required: false
    description: maximum number of trials until action fails
    default: "5"
  delay:
    required: false
    default: "5"
    description: deplay in seconts between trials

runs:
  using: docker
  image: Dockerfile
