name: cache node and npm deps
description: this action allows to cache both node and npm deps based on the package-lock.json file.

inputs:
  node-version:
    description: nodejs version to use
    default: 22.x
    required: false
  working-dir:
    description: the working directory of the application
    default: .
    required: false
  target-env:
    description: environemnt dev or prod
    default: dev
    required: false

runs:
  using: composite
  steps:
    - name: setup nodejs version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: cache deps
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ inputs.target-env }}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
    - name: install deps
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}
