name: cache node and npm deps
description: this action allows to cache both node and npm deps based on the package-lock.json file.

inputs:
  node-version:
    description: nodejs version to use
    default: 22.x
    required: false
  working-dir:
    description: the working directory of the application
    default: .
    required: false

runs:
  using: composite
  steps:
    - name: setup nodejs version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: cache deps
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}
    - name: install deps
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}
