name: composite action example using python

description: a simple composite action using python

inputs:
  name:
    description: name to greet
    required: true

runs:
  using: composite
  steps:
    - name: run a python script
      shell: python
      run: |
        import os
        import sys
        import datetime
        name = "${{ inputs.name }}"
        print(f"Hello from composite actions: {name}")
        print(f"greeting_time={datetime.datetime.now()}", file=open(os.environ['GITHUB_OUTPUT'], 'a'))
      env:
        GREET_NAME: ${{ inputs.name }}
