name: 02 - worflow events

on:
    push:
    pull_request:
    schedule: 
        - cron: "0/2 * * * *"
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest

        steps:
            - name: show the trigger
              run: |
                echo "Event Name: ${{ github.event_name }}"
