name: 04 - using actions

on:
    # push:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: printing dir structure
              run: |
                ls
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '22.x'
            - name: install deps
              run: npm ci
            - name: run unit tests
              run: npm run test
            