name: 07- using expressions

run-name: 07 - using expressions | DEBUG - ${{ inputs.debug == true && 'ON' || 'OFF' }}

on:
    # push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            -   name: "[debug] print start-up data"
                if: inputs.debug == true
                run: |
                    echo "debug mode is enabled"
                    echo "Trigerred by: ${{ github.event_name }}"
                    echo "Branch: ${{ github.ref }} (${{ github.ref_name }})"
                    echo "Commit SHA: ${{ github.sha }}"
                    echo "Runner OS: ${{ runner.os }}"
            -   name: "[debug] print when triggerred from main"
                if: inputs.debug == true && github.ref_name == 'main'
                run: |
                    echo "I was trigerred from main"
            -   name: "just fun"
                run: |
                    echo "just a fun"