name: 17 - 1 - custom actions composite

run-name: 17 - 1 - custom actions composite | env = ${{ inputs.target-env }}


on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                options:
                    - dev
                    - prod
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: 17-custom-actions/react-app
        steps:
            -   name: checkout code
                uses: actions/checkout@v4
            -   name: setup node and npm deps
                id: setup-deps
                uses: ./github/actions/composite-cache-deps
                with:
                    node-version: 22.x
                    working-dir: ${{ env.working-directory }}
                    target-env: ${{ inputs.target-env }}
            -   name: test
                run: |
                    npm run test
            -   name: build
                run: |
                    npm run build
                    