name: 17 - 3 - custom actions - docker

on:
    workflow_dispatch:
        inputs:
            url:
                type: choice
                options:
                    - https://www.google.com
                    - https://unrechable-site-for-test-ping-url.com 
                default: 'https://www.google.com'
            max_trials:
                description: maximum trial until action fails
                default: '5'

jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            -   name: code checkout
                uses: actions/checkout@v4
            -   name: ping url
                uses: ./.github/actions/docker-ping-url
                with:
                    url: ${{ inputs.url }}
                    max_trials: ${{ inputs.max_trials }}