name: test python composite action

on:
  # push:
  workflow_dispatch:

jobs:
  run-python-script:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: hit python composite action
        uses: ./.github/actions/python-composite-action
        id: python-composite-action
        with:
          name: "World"
      - name: print output from composite action
        run: |
          echo "Greeting time was ${{ steps.python-composite-action.outputs.greeting_time }}"